//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_History
    {
        public int add_id { get; set; }
        public int addressType_addressType_id { get; set; }
        public string firstName { get; set; }
        public string midName { get; set; }
        public string lastName { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string email { get; set; }
        public string add1 { get; set; }
        public string add2 { get; set; }
        public string phone { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string id_card_number { get; set; }
        public string relative_name_person_A { get; set; }
        public string relative_phone_person_A { get; set; }
        public string relative_name_person_B { get; set; }
        public string relative_phone_person_B { get; set; }
        public string relative_casen_person_A { get; set; }
        public string relative_casen_person_B { get; set; }
        public string job_titel { get; set; }
        public string addresscol { get; set; }
        public string userid { get; set; }
        public System.DateTime SysStartTime { get; set; }
        public System.DateTime SysEndTime { get; set; }
    }
}
