//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<addresstype> addresstypes { get; set; }
        public virtual DbSet<barcode> barcodes { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<measurement> measurements { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<order_has_product> order_has_product { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<shift> shifts { get; set; }
        public virtual DbSet<shiftadmin> shiftadmins { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<store_has_product> store_has_product { get; set; }
        public virtual DbSet<transvehcile> transvehciles { get; set; }
        public virtual DbSet<transvehcile_has_order> transvehcile_has_order { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<weight> weights { get; set; }
        public virtual DbSet<worker> workers { get; set; }
        public virtual DbSet<product> products { get; set; }
    
        public virtual ObjectResult<string> SP_Customer_Add_New(string a_Name, string a_Country, string a_City, string a_State, string a_Phone, string a_Fax, string a_Email, string aDRESS, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var a_NameParameter = a_Name != null ?
                new ObjectParameter("A_Name", a_Name) :
                new ObjectParameter("A_Name", typeof(string));
    
            var a_CountryParameter = a_Country != null ?
                new ObjectParameter("A_Country", a_Country) :
                new ObjectParameter("A_Country", typeof(string));
    
            var a_CityParameter = a_City != null ?
                new ObjectParameter("A_City", a_City) :
                new ObjectParameter("A_City", typeof(string));
    
            var a_StateParameter = a_State != null ?
                new ObjectParameter("A_State", a_State) :
                new ObjectParameter("A_State", typeof(string));
    
            var a_PhoneParameter = a_Phone != null ?
                new ObjectParameter("A_Phone", a_Phone) :
                new ObjectParameter("A_Phone", typeof(string));
    
            var a_FaxParameter = a_Fax != null ?
                new ObjectParameter("A_Fax", a_Fax) :
                new ObjectParameter("A_Fax", typeof(string));
    
            var a_EmailParameter = a_Email != null ?
                new ObjectParameter("A_Email", a_Email) :
                new ObjectParameter("A_Email", typeof(string));
    
            var aDRESSParameter = aDRESS != null ?
                new ObjectParameter("ADRESS", aDRESS) :
                new ObjectParameter("ADRESS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Customer_Add_New", a_NameParameter, a_CountryParameter, a_CityParameter, a_StateParameter, a_PhoneParameter, a_FaxParameter, a_EmailParameter, aDRESSParameter, new_identity, rec_found);
        }
    
        public virtual int SP_Customer_Delete(Nullable<int> cUSTOMER_ID, Nullable<int> aDD_ID)
        {
            var cUSTOMER_IDParameter = cUSTOMER_ID.HasValue ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(int));
    
            var aDD_IDParameter = aDD_ID.HasValue ?
                new ObjectParameter("ADD_ID", aDD_ID) :
                new ObjectParameter("ADD_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Customer_Delete", cUSTOMER_IDParameter, aDD_IDParameter);
        }
    
        public virtual ObjectResult<SP_Customer_ID_Result> SP_Customer_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Customer_ID_Result>("SP_Customer_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_Customer_Search_Result> SP_Customer_Search(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Customer_Search_Result>("SP_Customer_Search", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_Customer_To_ComboBox_Result> SP_Customer_To_ComboBox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Customer_To_ComboBox_Result>("SP_Customer_To_ComboBox");
        }
    
        public virtual ObjectResult<SP_Customer_To_DataGrid_Result> SP_Customer_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Customer_To_DataGrid_Result>("SP_Customer_To_DataGrid");
        }
    
        public virtual int SP_Customer_Update(Nullable<int> aDD_ID, string a_Name, string a_Country, string a_City, string a_State, string a_Phone, string a_Fax, string a_Email, string aDRESS, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var aDD_IDParameter = aDD_ID.HasValue ?
                new ObjectParameter("ADD_ID", aDD_ID) :
                new ObjectParameter("ADD_ID", typeof(int));
    
            var a_NameParameter = a_Name != null ?
                new ObjectParameter("A_Name", a_Name) :
                new ObjectParameter("A_Name", typeof(string));
    
            var a_CountryParameter = a_Country != null ?
                new ObjectParameter("A_Country", a_Country) :
                new ObjectParameter("A_Country", typeof(string));
    
            var a_CityParameter = a_City != null ?
                new ObjectParameter("A_City", a_City) :
                new ObjectParameter("A_City", typeof(string));
    
            var a_StateParameter = a_State != null ?
                new ObjectParameter("A_State", a_State) :
                new ObjectParameter("A_State", typeof(string));
    
            var a_PhoneParameter = a_Phone != null ?
                new ObjectParameter("A_Phone", a_Phone) :
                new ObjectParameter("A_Phone", typeof(string));
    
            var a_FaxParameter = a_Fax != null ?
                new ObjectParameter("A_Fax", a_Fax) :
                new ObjectParameter("A_Fax", typeof(string));
    
            var a_EmailParameter = a_Email != null ?
                new ObjectParameter("A_Email", a_Email) :
                new ObjectParameter("A_Email", typeof(string));
    
            var aDRESSParameter = aDRESS != null ?
                new ObjectParameter("ADRESS", aDRESS) :
                new ObjectParameter("ADRESS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Customer_Update", aDD_IDParameter, a_NameParameter, a_CountryParameter, a_CityParameter, a_StateParameter, a_PhoneParameter, a_FaxParameter, a_EmailParameter, aDRESSParameter, new_identity, rec_found);
        }
    
        public virtual ObjectResult<SP_flutter_Customer_Orders_Query_Result> SP_flutter_Customer_Orders_Query(string custmerPhone)
        {
            var custmerPhoneParameter = custmerPhone != null ?
                new ObjectParameter("CustmerPhone", custmerPhone) :
                new ObjectParameter("CustmerPhone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_flutter_Customer_Orders_Query_Result>("SP_flutter_Customer_Orders_Query", custmerPhoneParameter);
        }
    
        public virtual ObjectResult<SP_flutter_Query_Trans_Result> SP_flutter_Query_Trans(string custmerPhone)
        {
            var custmerPhoneParameter = custmerPhone != null ?
                new ObjectParameter("CustmerPhone", custmerPhone) :
                new ObjectParameter("CustmerPhone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_flutter_Query_Trans_Result>("SP_flutter_Query_Trans", custmerPhoneParameter);
        }
    
        public virtual ObjectResult<SP_LOGINSELECT_Result> SP_LOGINSELECT(string username, string password, ObjectParameter rec_found, ObjectParameter rolesName)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOGINSELECT_Result>("SP_LOGINSELECT", usernameParameter, passwordParameter, rec_found, rolesName);
        }
    
        public virtual ObjectResult<SP_LOGINSELECT_tmp_Result> SP_LOGINSELECT_tmp(string username, string password, ObjectParameter rec_found, ObjectParameter rolesName)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOGINSELECT_tmp_Result>("SP_LOGINSELECT_tmp", usernameParameter, passwordParameter, rec_found, rolesName);
        }
    
        public virtual ObjectResult<string> SP_Measurement_Add_New(string measurementName, Nullable<int> measurementKiloGram, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var measurementNameParameter = measurementName != null ?
                new ObjectParameter("MeasurementName", measurementName) :
                new ObjectParameter("MeasurementName", typeof(string));
    
            var measurementKiloGramParameter = measurementKiloGram.HasValue ?
                new ObjectParameter("MeasurementKiloGram", measurementKiloGram) :
                new ObjectParameter("MeasurementKiloGram", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Measurement_Add_New", measurementNameParameter, measurementKiloGramParameter, new_identity, rec_found);
        }
    
        public virtual int SP_Measurement_DELETE(Nullable<int> measurementId)
        {
            var measurementIdParameter = measurementId.HasValue ?
                new ObjectParameter("MeasurementId", measurementId) :
                new ObjectParameter("MeasurementId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Measurement_DELETE", measurementIdParameter);
        }
    
        public virtual ObjectResult<SP_Measurement_ID_Result> SP_Measurement_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Measurement_ID_Result>("SP_Measurement_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_Measurement_Search_Result> SP_Measurement_Search(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Measurement_Search_Result>("SP_Measurement_Search", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_Measurement_To_ComboBox_Result> SP_Measurement_To_ComboBox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Measurement_To_ComboBox_Result>("SP_Measurement_To_ComboBox");
        }
    
        public virtual ObjectResult<SP_Measurement_To_DataGrid_Result> SP_Measurement_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Measurement_To_DataGrid_Result>("SP_Measurement_To_DataGrid");
        }
    
        public virtual int SP_Measurement_Update(Nullable<int> measurementId, string measurementName, Nullable<int> measurementKiloGram, ObjectParameter rec_found)
        {
            var measurementIdParameter = measurementId.HasValue ?
                new ObjectParameter("MeasurementId", measurementId) :
                new ObjectParameter("MeasurementId", typeof(int));
    
            var measurementNameParameter = measurementName != null ?
                new ObjectParameter("MeasurementName", measurementName) :
                new ObjectParameter("MeasurementName", typeof(string));
    
            var measurementKiloGramParameter = measurementKiloGram.HasValue ?
                new ObjectParameter("MeasurementKiloGram", measurementKiloGram) :
                new ObjectParameter("MeasurementKiloGram", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Measurement_Update", measurementIdParameter, measurementNameParameter, measurementKiloGramParameter, rec_found);
        }
    
        public virtual int SP_Order_Add_New(Nullable<int> customerId, Nullable<int> storeId, Nullable<System.DateTime> orderDate, string orderNote)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var storeIdParameter = storeId.HasValue ?
                new ObjectParameter("StoreId", storeId) :
                new ObjectParameter("StoreId", typeof(int));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(System.DateTime));
    
            var orderNoteParameter = orderNote != null ?
                new ObjectParameter("OrderNote", orderNote) :
                new ObjectParameter("OrderNote", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Order_Add_New", customerIdParameter, storeIdParameter, orderDateParameter, orderNoteParameter);
        }
    
        public virtual int SP_Order_DELETE(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Order_DELETE", orderIdParameter);
        }
    
        public virtual ObjectResult<SP_Order_ID_Result> SP_Order_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_ID_Result>("SP_Order_ID", iDParameter);
        }
    
        public virtual int SP_Order_Items_Add_New(Nullable<int> orderId, Nullable<int> productId, Nullable<int> measureId, Nullable<int> weightId, Nullable<int> quantity)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var measureIdParameter = measureId.HasValue ?
                new ObjectParameter("measureId", measureId) :
                new ObjectParameter("measureId", typeof(int));
    
            var weightIdParameter = weightId.HasValue ?
                new ObjectParameter("weightId", weightId) :
                new ObjectParameter("weightId", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Order_Items_Add_New", orderIdParameter, productIdParameter, measureIdParameter, weightIdParameter, quantityParameter);
        }
    
        public virtual int SP_Order_Items_DELETE(Nullable<int> orderId, Nullable<int> productId, Nullable<int> measureId, Nullable<int> weightId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var measureIdParameter = measureId.HasValue ?
                new ObjectParameter("measureId", measureId) :
                new ObjectParameter("measureId", typeof(int));
    
            var weightIdParameter = weightId.HasValue ?
                new ObjectParameter("weightId", weightId) :
                new ObjectParameter("weightId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Order_Items_DELETE", orderIdParameter, productIdParameter, measureIdParameter, weightIdParameter);
        }
    
        public virtual ObjectResult<SP_Order_Items_ID_Result> SP_Order_Items_ID(Nullable<int> orderId, Nullable<int> productId, Nullable<int> measureId, Nullable<int> weightId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var measureIdParameter = measureId.HasValue ?
                new ObjectParameter("measureId", measureId) :
                new ObjectParameter("measureId", typeof(int));
    
            var weightIdParameter = weightId.HasValue ?
                new ObjectParameter("weightId", weightId) :
                new ObjectParameter("weightId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_Items_ID_Result>("SP_Order_Items_ID", orderIdParameter, productIdParameter, measureIdParameter, weightIdParameter);
        }
    
        public virtual ObjectResult<SP_Order_Items_To_DataGrid_Result> SP_Order_Items_To_DataGrid(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_Items_To_DataGrid_Result>("SP_Order_Items_To_DataGrid", orderIdParameter);
        }
    
        public virtual int SP_Order_Items_Update(Nullable<int> orderId, Nullable<int> productId, Nullable<int> measureId, Nullable<int> weightId, Nullable<int> newProductId, Nullable<int> newmeasureId, Nullable<int> newweightId, Nullable<int> newQuantity)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var measureIdParameter = measureId.HasValue ?
                new ObjectParameter("measureId", measureId) :
                new ObjectParameter("measureId", typeof(int));
    
            var weightIdParameter = weightId.HasValue ?
                new ObjectParameter("weightId", weightId) :
                new ObjectParameter("weightId", typeof(int));
    
            var newProductIdParameter = newProductId.HasValue ?
                new ObjectParameter("NewProductId", newProductId) :
                new ObjectParameter("NewProductId", typeof(int));
    
            var newmeasureIdParameter = newmeasureId.HasValue ?
                new ObjectParameter("NewmeasureId", newmeasureId) :
                new ObjectParameter("NewmeasureId", typeof(int));
    
            var newweightIdParameter = newweightId.HasValue ?
                new ObjectParameter("NewweightId", newweightId) :
                new ObjectParameter("NewweightId", typeof(int));
    
            var newQuantityParameter = newQuantity.HasValue ?
                new ObjectParameter("NewQuantity", newQuantity) :
                new ObjectParameter("NewQuantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Order_Items_Update", orderIdParameter, productIdParameter, measureIdParameter, weightIdParameter, newProductIdParameter, newmeasureIdParameter, newweightIdParameter, newQuantityParameter);
        }
    
        public virtual ObjectResult<SP_Order_Search_Result> SP_Order_Search(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_Search_Result>("SP_Order_Search", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_Order_To_DataGrid_Result> SP_Order_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_To_DataGrid_Result>("SP_Order_To_DataGrid");
        }
    
        public virtual int SP_Order_Trans_Vin_Add_New(Nullable<int> orderId, Nullable<int> transVinId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var transVinIdParameter = transVinId.HasValue ?
                new ObjectParameter("TransVinId", transVinId) :
                new ObjectParameter("TransVinId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Order_Trans_Vin_Add_New", orderIdParameter, transVinIdParameter);
        }
    
        public virtual int SP_Order_Trans_Vin_DELETE(Nullable<int> orderId, Nullable<int> transId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var transIdParameter = transId.HasValue ?
                new ObjectParameter("TransId", transId) :
                new ObjectParameter("TransId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Order_Trans_Vin_DELETE", orderIdParameter, transIdParameter);
        }
    
        public virtual ObjectResult<SP_Order_Trans_Vin_ID_Result> SP_Order_Trans_Vin_ID(Nullable<int> orderId, Nullable<int> transvehcileID)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var transvehcileIDParameter = transvehcileID.HasValue ?
                new ObjectParameter("transvehcileID", transvehcileID) :
                new ObjectParameter("transvehcileID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_Trans_Vin_ID_Result>("SP_Order_Trans_Vin_ID", orderIdParameter, transvehcileIDParameter);
        }
    
        public virtual ObjectResult<SP_Order_Trans_Vin_To_DataGrid_Result> SP_Order_Trans_Vin_To_DataGrid(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_Trans_Vin_To_DataGrid_Result>("SP_Order_Trans_Vin_To_DataGrid", orderIdParameter);
        }
    
        public virtual int SP_Order_Trans_Vin_Update(Nullable<int> orderId, Nullable<int> transId, Nullable<int> newOrderId, Nullable<int> newTransId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var transIdParameter = transId.HasValue ?
                new ObjectParameter("TransId", transId) :
                new ObjectParameter("TransId", typeof(int));
    
            var newOrderIdParameter = newOrderId.HasValue ?
                new ObjectParameter("NewOrderId", newOrderId) :
                new ObjectParameter("NewOrderId", typeof(int));
    
            var newTransIdParameter = newTransId.HasValue ?
                new ObjectParameter("NewTransId", newTransId) :
                new ObjectParameter("NewTransId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Order_Trans_Vin_Update", orderIdParameter, transIdParameter, newOrderIdParameter, newTransIdParameter);
        }
    
        public virtual int SP_Order_Update(Nullable<int> orderId, Nullable<int> customerId, Nullable<int> storeId, Nullable<System.DateTime> orderDate, string orderNote)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var storeIdParameter = storeId.HasValue ?
                new ObjectParameter("StoreId", storeId) :
                new ObjectParameter("StoreId", typeof(int));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(System.DateTime));
    
            var orderNoteParameter = orderNote != null ?
                new ObjectParameter("OrderNote", orderNote) :
                new ObjectParameter("OrderNote", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Order_Update", orderIdParameter, customerIdParameter, storeIdParameter, orderDateParameter, orderNoteParameter);
        }
    
        public virtual int SP_Product_DELETE(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Product_DELETE", productIdParameter);
        }
    
        public virtual ObjectResult<SP_Product_ID_Result> SP_Product_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Product_ID_Result>("SP_Product_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_Product_To_ComboBox_Result> SP_Product_To_ComboBox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Product_To_ComboBox_Result>("SP_Product_To_ComboBox");
        }
    
        public virtual ObjectResult<SP_Product_To_DataGrid_Result> SP_Product_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Product_To_DataGrid_Result>("SP_Product_To_DataGrid");
        }
    
        public virtual int SP_Product_Update(Nullable<int> productId, string productName, ObjectParameter rec_found)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Product_Update", productIdParameter, productNameParameter, rec_found);
        }
    
        public virtual ObjectResult<string> SP_Sales_BarCode(string barcode, string orderId, string prodductId, string weightId, ObjectParameter serial_found, ObjectParameter rec_found, ObjectParameter netCounter)
        {
            var barcodeParameter = barcode != null ?
                new ObjectParameter("Barcode", barcode) :
                new ObjectParameter("Barcode", typeof(string));
    
            var orderIdParameter = orderId != null ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(string));
    
            var prodductIdParameter = prodductId != null ?
                new ObjectParameter("ProdductId", prodductId) :
                new ObjectParameter("ProdductId", typeof(string));
    
            var weightIdParameter = weightId != null ?
                new ObjectParameter("weightId", weightId) :
                new ObjectParameter("weightId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Sales_BarCode", barcodeParameter, orderIdParameter, prodductIdParameter, weightIdParameter, serial_found, rec_found, netCounter);
        }
    
        public virtual ObjectResult<SP_Sales_BarCode_Check_Result> SP_Sales_BarCode_Check(string barcode, ObjectParameter rec_found)
        {
            var barcodeParameter = barcode != null ?
                new ObjectParameter("Barcode", barcode) :
                new ObjectParameter("Barcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Sales_BarCode_Check_Result>("SP_Sales_BarCode_Check", barcodeParameter, rec_found);
        }
    
        public virtual ObjectResult<SP_Sales_Order_Trans_Vin_Load_Result> SP_Sales_Order_Trans_Vin_Load(string transVehcileSerial)
        {
            var transVehcileSerialParameter = transVehcileSerial != null ?
                new ObjectParameter("transVehcileSerial", transVehcileSerial) :
                new ObjectParameter("transVehcileSerial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Sales_Order_Trans_Vin_Load_Result>("SP_Sales_Order_Trans_Vin_Load", transVehcileSerialParameter);
        }
    
        public virtual ObjectResult<string> SP_Shift_Admin_Add_New(string a_Name, string a_Country, string a_City, string a_State, string a_Phone, string a_Fax, string a_Email, string aDRESS, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var a_NameParameter = a_Name != null ?
                new ObjectParameter("A_Name", a_Name) :
                new ObjectParameter("A_Name", typeof(string));
    
            var a_CountryParameter = a_Country != null ?
                new ObjectParameter("A_Country", a_Country) :
                new ObjectParameter("A_Country", typeof(string));
    
            var a_CityParameter = a_City != null ?
                new ObjectParameter("A_City", a_City) :
                new ObjectParameter("A_City", typeof(string));
    
            var a_StateParameter = a_State != null ?
                new ObjectParameter("A_State", a_State) :
                new ObjectParameter("A_State", typeof(string));
    
            var a_PhoneParameter = a_Phone != null ?
                new ObjectParameter("A_Phone", a_Phone) :
                new ObjectParameter("A_Phone", typeof(string));
    
            var a_FaxParameter = a_Fax != null ?
                new ObjectParameter("A_Fax", a_Fax) :
                new ObjectParameter("A_Fax", typeof(string));
    
            var a_EmailParameter = a_Email != null ?
                new ObjectParameter("A_Email", a_Email) :
                new ObjectParameter("A_Email", typeof(string));
    
            var aDRESSParameter = aDRESS != null ?
                new ObjectParameter("ADRESS", aDRESS) :
                new ObjectParameter("ADRESS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Shift_Admin_Add_New", a_NameParameter, a_CountryParameter, a_CityParameter, a_StateParameter, a_PhoneParameter, a_FaxParameter, a_EmailParameter, aDRESSParameter, new_identity, rec_found);
        }
    
        public virtual int SP_Shift_Admin_DELETE(Nullable<int> shiftAdminID, Nullable<int> aDD_ID)
        {
            var shiftAdminIDParameter = shiftAdminID.HasValue ?
                new ObjectParameter("ShiftAdminID", shiftAdminID) :
                new ObjectParameter("ShiftAdminID", typeof(int));
    
            var aDD_IDParameter = aDD_ID.HasValue ?
                new ObjectParameter("ADD_ID", aDD_ID) :
                new ObjectParameter("ADD_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Shift_Admin_DELETE", shiftAdminIDParameter, aDD_IDParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Admin_ID_Result> SP_Shift_Admin_ID(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Admin_ID_Result>("SP_Shift_Admin_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Admin_SEARCH_Result> SP_Shift_Admin_SEARCH(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Admin_SEARCH_Result>("SP_Shift_Admin_SEARCH", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Admin_To_ComboBox_Result> SP_Shift_Admin_To_ComboBox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Admin_To_ComboBox_Result>("SP_Shift_Admin_To_ComboBox");
        }
    
        public virtual ObjectResult<SP_Shift_Admin_To_DataGrid_Result> SP_Shift_Admin_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Admin_To_DataGrid_Result>("SP_Shift_Admin_To_DataGrid");
        }
    
        public virtual int SP_Shift_Admin_Update(Nullable<int> aDD_ID, string a_Name, string a_Country, string a_City, string a_State, string a_Phone, string a_Fax, string a_Email, string aDRESS, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var aDD_IDParameter = aDD_ID.HasValue ?
                new ObjectParameter("ADD_ID", aDD_ID) :
                new ObjectParameter("ADD_ID", typeof(int));
    
            var a_NameParameter = a_Name != null ?
                new ObjectParameter("A_Name", a_Name) :
                new ObjectParameter("A_Name", typeof(string));
    
            var a_CountryParameter = a_Country != null ?
                new ObjectParameter("A_Country", a_Country) :
                new ObjectParameter("A_Country", typeof(string));
    
            var a_CityParameter = a_City != null ?
                new ObjectParameter("A_City", a_City) :
                new ObjectParameter("A_City", typeof(string));
    
            var a_StateParameter = a_State != null ?
                new ObjectParameter("A_State", a_State) :
                new ObjectParameter("A_State", typeof(string));
    
            var a_PhoneParameter = a_Phone != null ?
                new ObjectParameter("A_Phone", a_Phone) :
                new ObjectParameter("A_Phone", typeof(string));
    
            var a_FaxParameter = a_Fax != null ?
                new ObjectParameter("A_Fax", a_Fax) :
                new ObjectParameter("A_Fax", typeof(string));
    
            var a_EmailParameter = a_Email != null ?
                new ObjectParameter("A_Email", a_Email) :
                new ObjectParameter("A_Email", typeof(string));
    
            var aDRESSParameter = aDRESS != null ?
                new ObjectParameter("ADRESS", aDRESS) :
                new ObjectParameter("ADRESS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Shift_Admin_Update", aDD_IDParameter, a_NameParameter, a_CountryParameter, a_CityParameter, a_StateParameter, a_PhoneParameter, a_FaxParameter, a_EmailParameter, aDRESSParameter, new_identity, rec_found);
        }
    
        public virtual ObjectResult<string> SP_Shift_Main_Add_New(string shiftName, Nullable<int> shiftAdminId, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var shiftNameParameter = shiftName != null ?
                new ObjectParameter("ShiftName", shiftName) :
                new ObjectParameter("ShiftName", typeof(string));
    
            var shiftAdminIdParameter = shiftAdminId.HasValue ?
                new ObjectParameter("ShiftAdminId", shiftAdminId) :
                new ObjectParameter("ShiftAdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Shift_Main_Add_New", shiftNameParameter, shiftAdminIdParameter, new_identity, rec_found);
        }
    
        public virtual int SP_Shift_Main_DELETE(Nullable<int> shiftId)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Shift_Main_DELETE", shiftIdParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Main_ID_Result> SP_Shift_Main_ID(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Main_ID_Result>("SP_Shift_Main_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Main_Search_Result> SP_Shift_Main_Search(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Main_Search_Result>("SP_Shift_Main_Search", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Main_To_ComboBox_Result> SP_Shift_Main_To_ComboBox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Main_To_ComboBox_Result>("SP_Shift_Main_To_ComboBox");
        }
    
        public virtual ObjectResult<SP_Shift_Main_To_DataGrid_Result> SP_Shift_Main_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Main_To_DataGrid_Result>("SP_Shift_Main_To_DataGrid");
        }
    
        public virtual int SP_Shift_Main_Update(Nullable<int> shiftId, Nullable<int> shiftAdminId, string shiftName, ObjectParameter rec_found)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(int));
    
            var shiftAdminIdParameter = shiftAdminId.HasValue ?
                new ObjectParameter("ShiftAdminId", shiftAdminId) :
                new ObjectParameter("ShiftAdminId", typeof(int));
    
            var shiftNameParameter = shiftName != null ?
                new ObjectParameter("ShiftName", shiftName) :
                new ObjectParameter("ShiftName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Shift_Main_Update", shiftIdParameter, shiftAdminIdParameter, shiftNameParameter, rec_found);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Shift_Worker_Add_New(Nullable<int> shiftId, Nullable<int> workerId, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(int));
    
            var workerIdParameter = workerId.HasValue ?
                new ObjectParameter("WorkerId", workerId) :
                new ObjectParameter("WorkerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Shift_Worker_Add_New", shiftIdParameter, workerIdParameter, new_identity, rec_found);
        }
    
        public virtual int SP_Shift_Worker_DELETE(Nullable<int> shiftId, Nullable<int> workerId)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(int));
    
            var workerIdParameter = workerId.HasValue ?
                new ObjectParameter("WorkerId", workerId) :
                new ObjectParameter("WorkerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Shift_Worker_DELETE", shiftIdParameter, workerIdParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Worker_ID_Result> SP_Shift_Worker_ID(Nullable<int> shiftId, Nullable<int> workerId)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(int));
    
            var workerIdParameter = workerId.HasValue ?
                new ObjectParameter("WorkerId", workerId) :
                new ObjectParameter("WorkerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Worker_ID_Result>("SP_Shift_Worker_ID", shiftIdParameter, workerIdParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Worker_Search_Result> SP_Shift_Worker_Search(string sEARCH, Nullable<int> shiftId)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Worker_Search_Result>("SP_Shift_Worker_Search", sEARCHParameter, shiftIdParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Worker_To_DataGrid_Result> SP_Shift_Worker_To_DataGrid(Nullable<int> shiftId)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Worker_To_DataGrid_Result>("SP_Shift_Worker_To_DataGrid", shiftIdParameter);
        }
    
        public virtual ObjectResult<SP_Shift_Worker_To_DataGrid_All_Result> SP_Shift_Worker_To_DataGrid_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Shift_Worker_To_DataGrid_All_Result>("SP_Shift_Worker_To_DataGrid_All");
        }
    
        public virtual int SP_Shift_Worker_Update(Nullable<int> shiftId, Nullable<int> workerId, Nullable<int> workerId_Updated, ObjectParameter rec_found)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(int));
    
            var workerIdParameter = workerId.HasValue ?
                new ObjectParameter("WorkerId", workerId) :
                new ObjectParameter("WorkerId", typeof(int));
    
            var workerId_UpdatedParameter = workerId_Updated.HasValue ?
                new ObjectParameter("WorkerId_Updated", workerId_Updated) :
                new ObjectParameter("WorkerId_Updated", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Shift_Worker_Update", shiftIdParameter, workerIdParameter, workerId_UpdatedParameter, rec_found);
        }
    
        public virtual ObjectResult<SP_Store_Add_New_Result> SP_Store_Add_New(string store_Name, string a_Country, string store_Admin, string store_Location, ObjectParameter rec_found)
        {
            var store_NameParameter = store_Name != null ?
                new ObjectParameter("Store_Name", store_Name) :
                new ObjectParameter("Store_Name", typeof(string));
    
            var a_CountryParameter = a_Country != null ?
                new ObjectParameter("A_Country", a_Country) :
                new ObjectParameter("A_Country", typeof(string));
    
            var store_AdminParameter = store_Admin != null ?
                new ObjectParameter("Store_Admin", store_Admin) :
                new ObjectParameter("Store_Admin", typeof(string));
    
            var store_LocationParameter = store_Location != null ?
                new ObjectParameter("Store_Location", store_Location) :
                new ObjectParameter("Store_Location", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Store_Add_New_Result>("SP_Store_Add_New", store_NameParameter, a_CountryParameter, store_AdminParameter, store_LocationParameter, rec_found);
        }
    
        public virtual int SP_Store_Delete(Nullable<int> store_ID)
        {
            var store_IDParameter = store_ID.HasValue ?
                new ObjectParameter("Store_ID", store_ID) :
                new ObjectParameter("Store_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Store_Delete", store_IDParameter);
        }
    
        public virtual ObjectResult<SP_Store_ID_Result> SP_Store_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Store_ID_Result>("SP_Store_ID", iDParameter);
        }
    
        public virtual ObjectResult<string> SP_Store_Product_Add_New(Nullable<int> shiftId, Nullable<int> productId, Nullable<int> storeId, Nullable<int> weight, Nullable<System.DateTime> date1, string serialNumber, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var shiftIdParameter = shiftId.HasValue ?
                new ObjectParameter("ShiftId", shiftId) :
                new ObjectParameter("ShiftId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var storeIdParameter = storeId.HasValue ?
                new ObjectParameter("StoreId", storeId) :
                new ObjectParameter("StoreId", typeof(int));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(int));
    
            var date1Parameter = date1.HasValue ?
                new ObjectParameter("date1", date1) :
                new ObjectParameter("date1", typeof(System.DateTime));
    
            var serialNumberParameter = serialNumber != null ?
                new ObjectParameter("SerialNumber", serialNumber) :
                new ObjectParameter("SerialNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Store_Product_Add_New", shiftIdParameter, productIdParameter, storeIdParameter, weightParameter, date1Parameter, serialNumberParameter, new_identity, rec_found);
        }
    
        public virtual ObjectResult<SP_Store_Search_Result> SP_Store_Search(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Store_Search_Result>("SP_Store_Search", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_Store_To_ComboBox_Result> SP_Store_To_ComboBox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Store_To_ComboBox_Result>("SP_Store_To_ComboBox");
        }
    
        public virtual ObjectResult<SP_Store_To_DataGrid_Result> SP_Store_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Store_To_DataGrid_Result>("SP_Store_To_DataGrid");
        }
    
        public virtual ObjectResult<SP_Store_To_DataGrid_tmp_Result> SP_Store_To_DataGrid_tmp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Store_To_DataGrid_tmp_Result>("SP_Store_To_DataGrid_tmp");
        }
    
        public virtual int SP_Store_Update(Nullable<int> store_ID, string store_Name, string a_Country, string store_Admin, string store_Location)
        {
            var store_IDParameter = store_ID.HasValue ?
                new ObjectParameter("Store_ID", store_ID) :
                new ObjectParameter("Store_ID", typeof(int));
    
            var store_NameParameter = store_Name != null ?
                new ObjectParameter("Store_Name", store_Name) :
                new ObjectParameter("Store_Name", typeof(string));
    
            var a_CountryParameter = a_Country != null ?
                new ObjectParameter("A_Country", a_Country) :
                new ObjectParameter("A_Country", typeof(string));
    
            var store_AdminParameter = store_Admin != null ?
                new ObjectParameter("Store_Admin", store_Admin) :
                new ObjectParameter("Store_Admin", typeof(string));
    
            var store_LocationParameter = store_Location != null ?
                new ObjectParameter("Store_Location", store_Location) :
                new ObjectParameter("Store_Location", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Store_Update", store_IDParameter, store_NameParameter, a_CountryParameter, store_AdminParameter, store_LocationParameter);
        }
    
        public virtual ObjectResult<string> SP_Trans_Vin_Add_New(string txtDivername, string txtVinNum, string txtModel, string txtPhone, Nullable<int> txtCustomerId, string txtAddress, string txtSerial, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var txtDivernameParameter = txtDivername != null ?
                new ObjectParameter("TxtDivername", txtDivername) :
                new ObjectParameter("TxtDivername", typeof(string));
    
            var txtVinNumParameter = txtVinNum != null ?
                new ObjectParameter("TxtVinNum", txtVinNum) :
                new ObjectParameter("TxtVinNum", typeof(string));
    
            var txtModelParameter = txtModel != null ?
                new ObjectParameter("TxtModel", txtModel) :
                new ObjectParameter("TxtModel", typeof(string));
    
            var txtPhoneParameter = txtPhone != null ?
                new ObjectParameter("TxtPhone", txtPhone) :
                new ObjectParameter("TxtPhone", typeof(string));
    
            var txtCustomerIdParameter = txtCustomerId.HasValue ?
                new ObjectParameter("TxtCustomerId", txtCustomerId) :
                new ObjectParameter("TxtCustomerId", typeof(int));
    
            var txtAddressParameter = txtAddress != null ?
                new ObjectParameter("TxtAddress", txtAddress) :
                new ObjectParameter("TxtAddress", typeof(string));
    
            var txtSerialParameter = txtSerial != null ?
                new ObjectParameter("TxtSerial", txtSerial) :
                new ObjectParameter("TxtSerial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Trans_Vin_Add_New", txtDivernameParameter, txtVinNumParameter, txtModelParameter, txtPhoneParameter, txtCustomerIdParameter, txtAddressParameter, txtSerialParameter, new_identity, rec_found);
        }
    
        public virtual int SP_Trans_Vin_DELETE(Nullable<int> vinNo)
        {
            var vinNoParameter = vinNo.HasValue ?
                new ObjectParameter("VinNo", vinNo) :
                new ObjectParameter("VinNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Trans_Vin_DELETE", vinNoParameter);
        }
    
        public virtual ObjectResult<SP_Trans_Vin_ID_Result> SP_Trans_Vin_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Trans_Vin_ID_Result>("SP_Trans_Vin_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_TRANS_VIN_Search_Result> SP_TRANS_VIN_Search(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TRANS_VIN_Search_Result>("SP_TRANS_VIN_Search", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_Trans_Vin_To_ComboBox_Result> SP_Trans_Vin_To_ComboBox(Nullable<int> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Trans_Vin_To_ComboBox_Result>("SP_Trans_Vin_To_ComboBox", customerIdParameter);
        }
    
        public virtual ObjectResult<SP_Trans_Vin_To_DataGrid_Result> SP_Trans_Vin_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Trans_Vin_To_DataGrid_Result>("SP_Trans_Vin_To_DataGrid");
        }
    
        public virtual int SP_Trans_vin_Update(Nullable<int> vinNo, string txtDivername, string txtVinNum, string txtModel, string txtPhone, Nullable<int> txtCustomerId, string txtAddress, string txtSerial, ObjectParameter rec_found)
        {
            var vinNoParameter = vinNo.HasValue ?
                new ObjectParameter("VinNo", vinNo) :
                new ObjectParameter("VinNo", typeof(int));
    
            var txtDivernameParameter = txtDivername != null ?
                new ObjectParameter("TxtDivername", txtDivername) :
                new ObjectParameter("TxtDivername", typeof(string));
    
            var txtVinNumParameter = txtVinNum != null ?
                new ObjectParameter("TxtVinNum", txtVinNum) :
                new ObjectParameter("TxtVinNum", typeof(string));
    
            var txtModelParameter = txtModel != null ?
                new ObjectParameter("TxtModel", txtModel) :
                new ObjectParameter("TxtModel", typeof(string));
    
            var txtPhoneParameter = txtPhone != null ?
                new ObjectParameter("TxtPhone", txtPhone) :
                new ObjectParameter("TxtPhone", typeof(string));
    
            var txtCustomerIdParameter = txtCustomerId.HasValue ?
                new ObjectParameter("TxtCustomerId", txtCustomerId) :
                new ObjectParameter("TxtCustomerId", typeof(int));
    
            var txtAddressParameter = txtAddress != null ?
                new ObjectParameter("TxtAddress", txtAddress) :
                new ObjectParameter("TxtAddress", typeof(string));
    
            var txtSerialParameter = txtSerial != null ?
                new ObjectParameter("TxtSerial", txtSerial) :
                new ObjectParameter("TxtSerial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Trans_vin_Update", vinNoParameter, txtDivernameParameter, txtVinNumParameter, txtModelParameter, txtPhoneParameter, txtCustomerIdParameter, txtAddressParameter, txtSerialParameter, rec_found);
        }
    
        public virtual ObjectResult<string> SP_User_Add_New(string userName, string userPassword, Nullable<int> userRole, string a_Name, string a_Country, string a_City, string a_State, string a_Phone, string a_Fax, string a_Email, string aDRESS, ObjectParameter rec_found)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("userPassword", userPassword) :
                new ObjectParameter("userPassword", typeof(string));
    
            var userRoleParameter = userRole.HasValue ?
                new ObjectParameter("userRole", userRole) :
                new ObjectParameter("userRole", typeof(int));
    
            var a_NameParameter = a_Name != null ?
                new ObjectParameter("A_Name", a_Name) :
                new ObjectParameter("A_Name", typeof(string));
    
            var a_CountryParameter = a_Country != null ?
                new ObjectParameter("A_Country", a_Country) :
                new ObjectParameter("A_Country", typeof(string));
    
            var a_CityParameter = a_City != null ?
                new ObjectParameter("A_City", a_City) :
                new ObjectParameter("A_City", typeof(string));
    
            var a_StateParameter = a_State != null ?
                new ObjectParameter("A_State", a_State) :
                new ObjectParameter("A_State", typeof(string));
    
            var a_PhoneParameter = a_Phone != null ?
                new ObjectParameter("A_Phone", a_Phone) :
                new ObjectParameter("A_Phone", typeof(string));
    
            var a_FaxParameter = a_Fax != null ?
                new ObjectParameter("A_Fax", a_Fax) :
                new ObjectParameter("A_Fax", typeof(string));
    
            var a_EmailParameter = a_Email != null ?
                new ObjectParameter("A_Email", a_Email) :
                new ObjectParameter("A_Email", typeof(string));
    
            var aDRESSParameter = aDRESS != null ?
                new ObjectParameter("ADRESS", aDRESS) :
                new ObjectParameter("ADRESS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_User_Add_New", userNameParameter, userPasswordParameter, userRoleParameter, a_NameParameter, a_CountryParameter, a_CityParameter, a_StateParameter, a_PhoneParameter, a_FaxParameter, a_EmailParameter, aDRESSParameter, rec_found);
        }
    
        public virtual ObjectResult<SP_User_To_DataGrid_Result> SP_User_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_To_DataGrid_Result>("SP_User_To_DataGrid");
        }
    
        public virtual ObjectResult<SP_weight_To_ComboBox_Result> SP_weight_To_ComboBox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_weight_To_ComboBox_Result>("SP_weight_To_ComboBox");
        }
    
        public virtual ObjectResult<string> SP_Worker_Add_New(string a_Name, string a_Country, string a_City, string a_State, string a_Phone, string a_Fax, string a_Email, string aDRESS, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var a_NameParameter = a_Name != null ?
                new ObjectParameter("A_Name", a_Name) :
                new ObjectParameter("A_Name", typeof(string));
    
            var a_CountryParameter = a_Country != null ?
                new ObjectParameter("A_Country", a_Country) :
                new ObjectParameter("A_Country", typeof(string));
    
            var a_CityParameter = a_City != null ?
                new ObjectParameter("A_City", a_City) :
                new ObjectParameter("A_City", typeof(string));
    
            var a_StateParameter = a_State != null ?
                new ObjectParameter("A_State", a_State) :
                new ObjectParameter("A_State", typeof(string));
    
            var a_PhoneParameter = a_Phone != null ?
                new ObjectParameter("A_Phone", a_Phone) :
                new ObjectParameter("A_Phone", typeof(string));
    
            var a_FaxParameter = a_Fax != null ?
                new ObjectParameter("A_Fax", a_Fax) :
                new ObjectParameter("A_Fax", typeof(string));
    
            var a_EmailParameter = a_Email != null ?
                new ObjectParameter("A_Email", a_Email) :
                new ObjectParameter("A_Email", typeof(string));
    
            var aDRESSParameter = aDRESS != null ?
                new ObjectParameter("ADRESS", aDRESS) :
                new ObjectParameter("ADRESS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Worker_Add_New", a_NameParameter, a_CountryParameter, a_CityParameter, a_StateParameter, a_PhoneParameter, a_FaxParameter, a_EmailParameter, aDRESSParameter, new_identity, rec_found);
        }
    
        public virtual int SP_Worker_DELETE(Nullable<int> workerID, Nullable<int> aDD_ID)
        {
            var workerIDParameter = workerID.HasValue ?
                new ObjectParameter("WorkerID", workerID) :
                new ObjectParameter("WorkerID", typeof(int));
    
            var aDD_IDParameter = aDD_ID.HasValue ?
                new ObjectParameter("ADD_ID", aDD_ID) :
                new ObjectParameter("ADD_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Worker_DELETE", workerIDParameter, aDD_IDParameter);
        }
    
        public virtual ObjectResult<SP_Worker_ID_Result> SP_Worker_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Worker_ID_Result>("SP_Worker_ID", iDParameter);
        }
    
        public virtual ObjectResult<SP_Worker_SEARCH_Result> SP_Worker_SEARCH(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Worker_SEARCH_Result>("SP_Worker_SEARCH", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_Worker_To_ComboBox_Result> SP_Worker_To_ComboBox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Worker_To_ComboBox_Result>("SP_Worker_To_ComboBox");
        }
    
        public virtual int SP_Worker_Update(Nullable<int> aDD_ID, string a_Name, string a_Country, string a_City, string a_State, string a_Phone, string a_Fax, string a_Email, string aDRESS, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var aDD_IDParameter = aDD_ID.HasValue ?
                new ObjectParameter("ADD_ID", aDD_ID) :
                new ObjectParameter("ADD_ID", typeof(int));
    
            var a_NameParameter = a_Name != null ?
                new ObjectParameter("A_Name", a_Name) :
                new ObjectParameter("A_Name", typeof(string));
    
            var a_CountryParameter = a_Country != null ?
                new ObjectParameter("A_Country", a_Country) :
                new ObjectParameter("A_Country", typeof(string));
    
            var a_CityParameter = a_City != null ?
                new ObjectParameter("A_City", a_City) :
                new ObjectParameter("A_City", typeof(string));
    
            var a_StateParameter = a_State != null ?
                new ObjectParameter("A_State", a_State) :
                new ObjectParameter("A_State", typeof(string));
    
            var a_PhoneParameter = a_Phone != null ?
                new ObjectParameter("A_Phone", a_Phone) :
                new ObjectParameter("A_Phone", typeof(string));
    
            var a_FaxParameter = a_Fax != null ?
                new ObjectParameter("A_Fax", a_Fax) :
                new ObjectParameter("A_Fax", typeof(string));
    
            var a_EmailParameter = a_Email != null ?
                new ObjectParameter("A_Email", a_Email) :
                new ObjectParameter("A_Email", typeof(string));
    
            var aDRESSParameter = aDRESS != null ?
                new ObjectParameter("ADRESS", aDRESS) :
                new ObjectParameter("ADRESS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Worker_Update", aDD_IDParameter, a_NameParameter, a_CountryParameter, a_CityParameter, a_StateParameter, a_PhoneParameter, a_FaxParameter, a_EmailParameter, aDRESSParameter, new_identity, rec_found);
        }
    
        public virtual ObjectResult<SP_Workers_To_DataGrid_Result> SP_Workers_To_DataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Workers_To_DataGrid_Result>("SP_Workers_To_DataGrid");
        }
    
        public virtual ObjectResult<SP_Sales_Order_Trans_Vin_display_Result> SP_Sales_Order_Trans_Vin_display()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Sales_Order_Trans_Vin_display_Result>("SP_Sales_Order_Trans_Vin_display");
        }
    
        public virtual ObjectResult<string> SP_Product_Add_New(string productName, Nullable<double> productPrice, ObjectParameter new_identity, ObjectParameter rec_found)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var productPriceParameter = productPrice.HasValue ?
                new ObjectParameter("ProductPrice", productPrice) :
                new ObjectParameter("ProductPrice", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Product_Add_New", productNameParameter, productPriceParameter, new_identity, rec_found);
        }
    
        public virtual ObjectResult<SP_Product_Search_Result> SP_Product_Search(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Product_Search_Result>("SP_Product_Search", sEARCHParameter);
        }
    
        public virtual int SP_Update_Product_Price(Nullable<int> productId, string productName, Nullable<double> productPrice)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var productPriceParameter = productPrice.HasValue ?
                new ObjectParameter("ProductPrice", productPrice) :
                new ObjectParameter("ProductPrice", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Product_Price", productIdParameter, productNameParameter, productPriceParameter);
        }
    }
}
