//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_History
    {
        public int order_id { get; set; }
        public int customers_Customers_id { get; set; }
        public Nullable<int> users_user_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string notic { get; set; }
        public int store_store_id { get; set; }
        public Nullable<int> order_state { get; set; }
        public string userid { get; set; }
        public System.DateTime SysStartTime { get; set; }
        public System.DateTime SysEndTime { get; set; }
    }
}
