//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_History
    {
        public int product_id { get; set; }
        public string productName { get; set; }
        public Nullable<double> TodayPrice { get; set; }
        public Nullable<System.DateTime> PriceUpdateTime { get; set; }
        public byte[] PrductImg { get; set; }
        public string userid { get; set; }
        public System.DateTime SysStartTime { get; set; }
        public System.DateTime SysEndTime { get; set; }
    }
}
