//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_has_product_has_order
    {
        public int store_has_product_store_store_id { get; set; }
        public int store_has_product_product_product_id { get; set; }
        public int store_has_product_shift_shift_id { get; set; }
        public string store_has_product_barcode_serialNumber { get; set; }
        public int store_has_product_weight_weight_id { get; set; }
        public int order_order_id { get; set; }
        public Nullable<int> v_id { get; set; }
    
        public virtual order order { get; set; }
        public virtual store_has_product store_has_product { get; set; }
    }
}
