//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transvehcile_History
    {
        public int v_id { get; set; }
        public int customers_Customers_id { get; set; }
        public string transVehcile_driver_name { get; set; }
        public string transVehcile_num { get; set; }
        public string transVehcile_model { get; set; }
        public string transVehcile_serial { get; set; }
        public string transVehcile_phone { get; set; }
        public string transVehcile_add { get; set; }
        public string userid { get; set; }
        public System.DateTime SysStartTime { get; set; }
        public System.DateTime SysEndTime { get; set; }
    }
}
