//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_has_product
    {
        public int order_order_id { get; set; }
        public int product_product_id { get; set; }
        public string Quantity { get; set; }
        public int measurement_measure_id { get; set; }
        public int weight_weight_id { get; set; }
    
        public virtual measurement measurement { get; set; }
        public virtual order order { get; set; }
        public virtual product product { get; set; }
        public virtual weight weight { get; set; }
    }
}
